version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    container_name: elasticsearch_autocomplete
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
      - "9300:9300"